steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/cloudaleapi/aleapi', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/cloudaleapi/aleapi']
# Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'aleapi', '--image', 'gcr.io/cloudaleapi/aleapi', '--region', 'us-east1', '--platform', 'managed', '--allow-unauthenticated']
images:
- gcr.io/cloudaleapi/aleapi
