"""empty message

Revision ID: 317ac4487c72
Revises:
Create Date: 2020-06-14 22:30:39.078316

"""
from sqlalchemy_utils import ChoiceType
from alembic import op
import sqlalchemy as sa
from domain.enums import GameStatusEnum


# revision identifiers, used by Alembic.
revision = "317ac4487c72"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "boards",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("rows", sa.Integer(), nullable=False),
        sa.Column("cols", sa.Integer(), nullable=False),
        sa.Column("mines", sa.Integer(), nullable=False),
        sa.Column("slots", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "players",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "games",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("player_id", sa.String(), nullable=False),
        sa.Column("board_id", sa.String(), nullable=False),
        sa.Column("status", ChoiceType(GameStatusEnum, impl=sa.Integer())),
        sa.ForeignKeyConstraint(["board_id"], ["boards.id"],),
        sa.ForeignKeyConstraint(["player_id"], ["players.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("games")
    op.drop_table("players")
    op.drop_table("boards")
    # ### end Alembic commands ###
