"""empty message

Revision ID: 5403eb84bf74
Revises: 317ac4487c72
Create Date: 2020-06-17 07:44:47.421466

"""
from alembic import op
from datetime import datetime
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "5403eb84bf74"
down_revision = "317ac4487c72"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("games", sa.Column("end_time", sa.DateTime(), nullable=True))
    op.add_column(
        "games",
        sa.Column("start_time", sa.DateTime(), nullable=True, default=datetime.utcnow),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("games", "start_time")
    op.drop_column("games", "end_time")
    # ### end Alembic commands ###
